### ISSUE TITLE
Syntax-highlighting DuoTone Dark omissions

### ISSUE THREAD

**Issue by atelierbram** [CodePen/CodePen-Bug-Reporting-Only#104]
On syntax-highlighting for the new DuoTone Dark theme: missing the light orange for numbers in `CSS`, variables in `JS` and so on. Seems like [this style-block  from linenr. 67](https://github.com/atelierbram/syntax-highlighting/blob/master/duotones/output/codemirror/duotone-dark-cm.css) is missing:

```css
.cm-s-duotone-dark-cm span.cm-atom, 
.cm-s-duotone-dark-cm span.cm-number, 
.cm-s-duotone-dark-cm span.cm-keyword,
.cm-s-duotone-dark-cm span.cm-variable, 
.cm-s-duotone-dark-cm span.cm-attribute, 
.cm-s-duotone-dark-cm span.cm-quote, 
.cm-s-duotone-dark-cm span.cm-hr, 
.cm-s-duotone-dark-cm span.cm-link { 
   color: #ffcc99; 
}
```

Not seeing theme specific cursor style (`background-color`) declared

```css
.cm-fat-cursor .CodeMirror-cursor {
  background: rgba(255,168,82,0.5);
}
```
