### ISSUE TITLE
Email confirmation text is the same color as the background

### ISSUE THREAD

**Issue by bencodezen** [CodePen/CodePen-Bug-Reporting-Only#145]
Stumbled on this by accident after submitting a suggestion via the Private contact form. 

<img width="785" alt="screen shot 2016-03-09 at 5 39 33 pm" src="https://cloud.githubusercontent.com/assets/4836334/13653182/14f97afe-e61e-11e5-9c15-dc21a323df30.png">

It looks like there is a specificity issue with selector overriding the default text color (white) due to a `.paidHeading` class:

```css
.embed .confirm h2.paidHeading {
    ...
    color: #222;
    ...
}

.confirm h2 {
    font-family: inherit;
    color: #ffffff;
}
```

Hope this helps!
