### ISSUE TITLE
Weird Sass + @charset Thing

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#224]
Test case: http://codepen.io/team/codepen/pen/RaMyxg

1) Use a unicode character thing in SCSS

```scss
body::before {
  content: "❤";
}
```

2) ALSO use an `@import` statement, which are REQUIRED to be FIRST in CSS to work., like

```scss
@import url(https://fonts.googleapis.com/css?family=Raleway);

body::before {
  content: "❤";
}
```

3) Compiled CSS has the inserted `@charset` rule:

```css
@charset "UTF-8";
@import url(https://fonts.googleapis.com/css?family=Raleway);
body::before {
  content: "❤";
}
```

4) Thus the font doesn't work.

It's probably the Sass compiler adding that. Not sure what to do about this one.
